import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header";
import ClientProviders from "@/components/providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProviders>
        <main className="flex flex-col text-stone-100 bg-[rgb(25,33,52)] bg-[linear-gradient(180deg,rgba(25,33,52,1)28%,rgba(7,8,21,1)75%)]  min-h-screen w-screen font-[family-name:var(--font-geist-sans)]">
        <Header />
        <div className="grid container place-items-center w-4/5 mx-auto">
        {children}
        </div>
        </main>
        </ClientProviders>
      </body>
    </html>
  );
}
